"""initial schema

Revision ID: e8964ad5e49e
Revises: 
Create Date: 2026-10-10 02:19:36.308661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8964ad5e49e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('instagram_handle', sa.String(length=30), nullable=True),
    sa.Column('upi_id', sa.String(length=100), nullable=True),
    sa.Column('email_opt_in', sa.Boolean(), nullable=False),
    sa.Column('whatsapp_opt_in', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('brand', 'creator')", name=op.f('ck_users_role_valid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_table('campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('budget_paise', sa.BigInteger(), nullable=False),
    sa.Column('fee_paise', sa.BigInteger(), nullable=False),
    sa.Column('slots', sa.Integer(), nullable=False),
    sa.Column('apply_deadline', sa.DateTime(timezone=True), nullable=False),
    sa.Column('submit_deadline', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('filled_slots', sa.Integer(), nullable=False),
    sa.Column('reserved_paise', sa.BigInteger(), nullable=False),
    sa.Column('spent_paise', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('active', 'cancelled')", name=op.f('ck_campaigns_status_valid')),
    sa.CheckConstraint('apply_deadline < submit_deadline', name=op.f('ck_campaigns_deadlines_ordered')),
    sa.CheckConstraint('fee_paise > 0', name=op.f('ck_campaigns_fee_positive')),
    sa.CheckConstraint('filled_slots >= 0 AND filled_slots <= slots', name=op.f('ck_campaigns_filled_within_slots')),
    sa.CheckConstraint('reserved_paise + spent_paise <= budget_paise', name=op.f('ck_campaigns_within_budget')),
    sa.CheckConstraint('reserved_paise >= 0 AND spent_paise >= 0', name=op.f('ck_campaigns_money_non_negative')),
    sa.CheckConstraint('slots > 0', name=op.f('ck_campaigns_slots_positive')),
    sa.ForeignKeyConstraint(['brand_id'], ['users.id'], name=op.f('fk_campaigns_brand_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_campaigns'))
    )
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.String(length=10), nullable=False),
    sa.Column('event', sa.String(length=40), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('skip_reason', sa.String(length=100), nullable=True),
    sa.Column('send_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("channel IN ('email', 'whatsapp')", name=op.f('ck_notifications_channel_valid')),
    sa.CheckConstraint("status IN ('queued', 'sent', 'skipped')", name=op.f('ck_notifications_status_valid')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notifications_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    op.create_index('ix_notifications_due', 'notifications', ['status', 'send_at'], unique=False)
    op.create_table('wallets',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('balance_paise', sa.BigInteger(), nullable=False),
    sa.CheckConstraint('balance_paise >= 0', name=op.f('ck_wallets_balance_never_negative')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_wallets_user_id_users')),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_wallets'))
    )
    op.create_table('withdrawals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount_paise', sa.BigInteger(), nullable=False),
    sa.Column('upi_id', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('failure_reason', sa.String(length=200), nullable=True),
    sa.Column('provider_ref', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('processing', 'succeeded', 'failed')", name=op.f('ck_withdrawals_status_valid')),
    sa.CheckConstraint('amount_paise > 0', name=op.f('ck_withdrawals_amount_positive')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_withdrawals_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_withdrawals'))
    )
    op.create_table('applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('fee_paise', sa.BigInteger(), nullable=True),
    sa.Column('revision_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('revision_count BETWEEN 0 AND 2', name=op.f('ck_applications_revisions_capped')),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('fk_applications_campaign_id_campaigns')),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], name=op.f('fk_applications_creator_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_applications')),
    sa.UniqueConstraint('campaign_id', 'creator_id', name=op.f('uq_applications_campaign_id'))
    )
    op.create_table('application_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('from_status', sa.String(length=20), nullable=True),
    sa.Column('to_status', sa.String(length=20), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], name=op.f('fk_application_events_application_id_applications')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_application_events'))
    )
    op.create_table('payouts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('fee_paise', sa.BigInteger(), nullable=False),
    sa.Column('platform_fee_paise', sa.BigInteger(), nullable=False),
    sa.Column('gst_paise', sa.BigInteger(), nullable=False),
    sa.Column('tds_paise', sa.BigInteger(), nullable=False),
    sa.Column('net_paise', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], name=op.f('fk_payouts_application_id_applications')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payouts')),
    sa.UniqueConstraint('application_id', name=op.f('uq_payouts_application_id'))
    )
    op.create_table('submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=300), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], name=op.f('fk_submissions_application_id_applications')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_submissions'))
    )
    op.create_table('ledger_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=12), nullable=False),
    sa.Column('amount_paise', sa.BigInteger(), nullable=False),
    sa.Column('balance_after_paise', sa.BigInteger(), nullable=False),
    sa.Column('payout_id', sa.Integer(), nullable=True),
    sa.Column('withdrawal_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind IN ('payout', 'withdrawal', 'refund')", name=op.f('ck_ledger_entries_kind_valid')),
    sa.ForeignKeyConstraint(['payout_id'], ['payouts.id'], name=op.f('fk_ledger_entries_payout_id_payouts')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_ledger_entries_user_id_users')),
    sa.ForeignKeyConstraint(['withdrawal_id'], ['withdrawals.id'], name=op.f('fk_ledger_entries_withdrawal_id_withdrawals')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ledger_entries'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ledger_entries')
    op.drop_table('submissions')
    op.drop_table('payouts')
    op.drop_table('application_events')
    op.drop_table('applications')
    op.drop_table('withdrawals')
    op.drop_table('wallets')
    op.drop_index('ix_notifications_due', table_name='notifications')
    op.drop_table('notifications')
    op.drop_table('campaigns')
    op.drop_table('users')
    # ### end Alembic commands ###
